/********************************************************************************
** Form generated from reading UI file 'buttons.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BUTTONS_H
#define UI_BUTTONS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "radiobuttons.h"

QT_BEGIN_NAMESPACE

class Ui_Buttons
{
public:
    QPushButton *BUTTON_RD5;
    QLabel *label_73;
    QPushButton *BUTTON_RC3;
    QLabel *label_132;
    QPushButton *BUTTON_RG1;
    QLabel *label_100;
    QLabel *label_122;
    QLabel *label_108;
    QPushButton *BUTTON_RE0;
    QLabel *label_98;
    QLabel *label_106;
    QPushButton *BUTTON_RH4;
    QPushButton *BUTTON_RH3;
    QPushButton *BUTTON_RC2;
    QPushButton *BUTTON_RE7;
    QPushButton *BUTTON_RA1;
    QPushButton *BUTTON_RH5;
    QPushButton *BUTTON_RJ4;
    QLabel *label_101;
    QPushButton *BUTTON_RG7;
    QPushButton *BUTTON_RA3;
    QPushButton *BUTTON_RD6;
    QLabel *label_91;
    QPushButton *BUTTON_RJ6;
    QPushButton *BUTTON_RA7;
    QLabel *label_86;
    QPushButton *BUTTON_RJ1;
    QPushButton *BUTTON_RA2;
    QPushButton *BUTTON_RA0;
    QPushButton *BUTTON_RJ5;
    QLabel *label_112;
    QLabel *label_88;
    QLabel *label_113;
    QLabel *label_83;
    QLabel *label_137;
    QPushButton *BUTTON_RG4;
    QLabel *label_96;
    QLabel *label_80;
    QLabel *label_95;
    QPushButton *BUTTON_RJ3;
    QPushButton *BUTTON_RB4;
    QLabel *label_107;
    QLabel *label_133;
    QPushButton *BUTTON_RF2;
    QPushButton *BUTTON_RF3;
    QPushButton *BUTTON_RC7;
    QLabel *label_85;
    QPushButton *BUTTON_RB5;
    QPushButton *BUTTON_RF5;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_125;
    QLabel *label_131;
    QLabel *label_124;
    QLabel *label_103;
    QPushButton *BUTTON_RH2;
    QPushButton *BUTTON_RD2;
    QLabel *label_118;
    QLabel *label_75;
    QPushButton *BUTTON_RH6;
    QLabel *label_115;
    QPushButton *BUTTON_RE4;
    QLabel *label_117;
    QPushButton *BUTTON_RC6;
    QPushButton *BUTTON_RG2;
    QLabel *label_116;
    QLabel *label_126;
    QLabel *label_92;
    QPushButton *BUTTON_RF6;
    QLabel *label_138;
    QPushButton *BUTTON_RF1;
    QLabel *label_36;
    QPushButton *BUTTON_RC5;
    QPushButton *BUTTON_RB0;
    QLabel *label_77;
    QLabel *label_136;
    QLabel *label_139;
    QLabel *label_93;
    QPushButton *BUTTON_RB2;
    QLabel *label_123;
    QPushButton *BUTTON_RE3;
    QPushButton *BUTTON_RJ0;
    QPushButton *BUTTON_RD7;
    QPushButton *BUTTON_RC0;
    QPushButton *BUTTON_RG0;
    QLabel *label_76;
    QPushButton *BUTTON_RG5;
    QLabel *label_102;
    QLabel *label_81;
    QPushButton *BUTTON_RG3;
    QPushButton *BUTTON_RH1;
    QLabel *label_110;
    QPushButton *BUTTON_RJ7;
    QLabel *label_130;
    QLabel *label_105;
    QLabel *label_89;
    QPushButton *BUTTON_RE2;
    QLabel *label_82;
    QPushButton *BUTTON_RH0;
    QPushButton *BUTTON_RB3;
    QPushButton *BUTTON_RE6;
    QLabel *label_104;
    QPushButton *BUTTON_RG6;
    QLabel *label_90;
    QLabel *label_109;
    QPushButton *BUTTON_RC4;
    QLabel *label_119;
    QLabel *label_135;
    QLabel *label_79;
    QPushButton *BUTTON_RB7;
    QPushButton *BUTTON_RB6;
    QPushButton *BUTTON_RE1;
    QLabel *label_134;
    QPushButton *BUTTON_RA5;
    QPushButton *BUTTON_RF0;
    QLabel *label_72;
    QLabel *label_127;
    QLabel *label_94;
    QPushButton *BUTTON_RA4;
    QLabel *label_74;
    QLabel *label_84;
    QPushButton *BUTTON_RF7;
    QLabel *label_97;
    QPushButton *BUTTON_RC1;
    QPushButton *BUTTON_RJ2;
    QPushButton *BUTTON_RD1;
    QLabel *label_87;
    QLabel *label_114;
    QPushButton *BUTTON_RD0;
    QLabel *label_78;
    QPushButton *BUTTON_RH7;
    QPushButton *BUTTON_RD3;
    QLabel *label_111;
    QPushButton *BUTTON_RE5;
    QLabel *label_129;
    QLabel *label_128;
    QPushButton *BUTTON_RF4;
    QPushButton *BUTTON_RB1;
    QLabel *label_120;
    QPushButton *BUTTON_RA6;
    QLabel *label_99;
    QLabel *label_140;
    QLabel *label_121;
    QPushButton *BUTTON_RD4;
    RadioButtons *J10;

    void setupUi(QWidget *Buttons)
    {
        if (Buttons->objectName().isEmpty())
            Buttons->setObjectName(QStringLiteral("Buttons"));
        Buttons->resize(450, 320);
        BUTTON_RD5 = new QPushButton(Buttons);
        BUTTON_RD5->setObjectName(QStringLiteral("BUTTON_RD5"));
        BUTTON_RD5->setGeometry(QRect(220, 220, 20, 20));
        label_73 = new QLabel(Buttons);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(95, 240, 30, 20));
        label_73->setAlignment(Qt::AlignCenter);
        BUTTON_RC3 = new QPushButton(Buttons);
        BUTTON_RC3->setObjectName(QStringLiteral("BUTTON_RC3"));
        BUTTON_RC3->setGeometry(QRect(180, 140, 20, 20));
        label_132 = new QLabel(Buttons);
        label_132->setObjectName(QStringLiteral("label_132"));
        label_132->setGeometry(QRect(375, 280, 30, 20));
        label_132->setAlignment(Qt::AlignCenter);
        BUTTON_RG1 = new QPushButton(Buttons);
        BUTTON_RG1->setObjectName(QStringLiteral("BUTTON_RG1"));
        BUTTON_RG1->setGeometry(QRect(340, 60, 20, 20));
        label_100 = new QLabel(Buttons);
        label_100->setObjectName(QStringLiteral("label_100"));
        label_100->setGeometry(QRect(215, 280, 30, 20));
        label_100->setAlignment(Qt::AlignCenter);
        label_122 = new QLabel(Buttons);
        label_122->setObjectName(QStringLiteral("label_122"));
        label_122->setGeometry(QRect(335, 200, 30, 20));
        label_122->setAlignment(Qt::AlignCenter);
        label_108 = new QLabel(Buttons);
        label_108->setObjectName(QStringLiteral("label_108"));
        label_108->setGeometry(QRect(255, 280, 30, 20));
        label_108->setAlignment(Qt::AlignCenter);
        BUTTON_RE0 = new QPushButton(Buttons);
        BUTTON_RE0->setObjectName(QStringLiteral("BUTTON_RE0"));
        BUTTON_RE0->setGeometry(QRect(260, 20, 20, 20));
        BUTTON_RE0->setCursor(QCursor(Qt::PointingHandCursor));
        label_98 = new QLabel(Buttons);
        label_98->setObjectName(QStringLiteral("label_98"));
        label_98->setGeometry(QRect(215, 200, 30, 20));
        label_98->setAlignment(Qt::AlignCenter);
        label_106 = new QLabel(Buttons);
        label_106->setObjectName(QStringLiteral("label_106"));
        label_106->setGeometry(QRect(255, 200, 30, 20));
        label_106->setAlignment(Qt::AlignCenter);
        BUTTON_RH4 = new QPushButton(Buttons);
        BUTTON_RH4->setObjectName(QStringLiteral("BUTTON_RH4"));
        BUTTON_RH4->setGeometry(QRect(380, 180, 20, 20));
        BUTTON_RH3 = new QPushButton(Buttons);
        BUTTON_RH3->setObjectName(QStringLiteral("BUTTON_RH3"));
        BUTTON_RH3->setGeometry(QRect(380, 140, 20, 20));
        BUTTON_RC2 = new QPushButton(Buttons);
        BUTTON_RC2->setObjectName(QStringLiteral("BUTTON_RC2"));
        BUTTON_RC2->setGeometry(QRect(180, 100, 20, 20));
        BUTTON_RE7 = new QPushButton(Buttons);
        BUTTON_RE7->setObjectName(QStringLiteral("BUTTON_RE7"));
        BUTTON_RE7->setGeometry(QRect(260, 300, 20, 20));
        BUTTON_RA1 = new QPushButton(Buttons);
        BUTTON_RA1->setObjectName(QStringLiteral("BUTTON_RA1"));
        BUTTON_RA1->setGeometry(QRect(100, 60, 20, 20));
        BUTTON_RH5 = new QPushButton(Buttons);
        BUTTON_RH5->setObjectName(QStringLiteral("BUTTON_RH5"));
        BUTTON_RH5->setGeometry(QRect(380, 220, 20, 20));
        BUTTON_RJ4 = new QPushButton(Buttons);
        BUTTON_RJ4->setObjectName(QStringLiteral("BUTTON_RJ4"));
        BUTTON_RJ4->setGeometry(QRect(420, 180, 20, 20));
        label_101 = new QLabel(Buttons);
        label_101->setObjectName(QStringLiteral("label_101"));
        label_101->setGeometry(QRect(255, 160, 30, 20));
        label_101->setAlignment(Qt::AlignCenter);
        BUTTON_RG7 = new QPushButton(Buttons);
        BUTTON_RG7->setObjectName(QStringLiteral("BUTTON_RG7"));
        BUTTON_RG7->setGeometry(QRect(340, 300, 20, 20));
        BUTTON_RA3 = new QPushButton(Buttons);
        BUTTON_RA3->setObjectName(QStringLiteral("BUTTON_RA3"));
        BUTTON_RA3->setGeometry(QRect(100, 140, 20, 20));
        BUTTON_RD6 = new QPushButton(Buttons);
        BUTTON_RD6->setObjectName(QStringLiteral("BUTTON_RD6"));
        BUTTON_RD6->setGeometry(QRect(220, 260, 20, 20));
        label_91 = new QLabel(Buttons);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(175, 120, 30, 20));
        label_91->setAlignment(Qt::AlignCenter);
        BUTTON_RJ6 = new QPushButton(Buttons);
        BUTTON_RJ6->setObjectName(QStringLiteral("BUTTON_RJ6"));
        BUTTON_RJ6->setGeometry(QRect(420, 260, 20, 20));
        BUTTON_RA7 = new QPushButton(Buttons);
        BUTTON_RA7->setObjectName(QStringLiteral("BUTTON_RA7"));
        BUTTON_RA7->setGeometry(QRect(100, 300, 20, 20));
        label_86 = new QLabel(Buttons);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(175, 80, 30, 20));
        label_86->setAlignment(Qt::AlignCenter);
        BUTTON_RJ1 = new QPushButton(Buttons);
        BUTTON_RJ1->setObjectName(QStringLiteral("BUTTON_RJ1"));
        BUTTON_RJ1->setGeometry(QRect(420, 60, 20, 20));
        BUTTON_RA2 = new QPushButton(Buttons);
        BUTTON_RA2->setObjectName(QStringLiteral("BUTTON_RA2"));
        BUTTON_RA2->setGeometry(QRect(100, 100, 20, 20));
        BUTTON_RA0 = new QPushButton(Buttons);
        BUTTON_RA0->setObjectName(QStringLiteral("BUTTON_RA0"));
        BUTTON_RA0->setGeometry(QRect(100, 20, 20, 20));
        BUTTON_RA0->setCursor(QCursor(Qt::PointingHandCursor));
        BUTTON_RA0->setFocusPolicy(Qt::StrongFocus);
        BUTTON_RJ5 = new QPushButton(Buttons);
        BUTTON_RJ5->setObjectName(QStringLiteral("BUTTON_RJ5"));
        BUTTON_RJ5->setGeometry(QRect(420, 220, 20, 20));
        label_112 = new QLabel(Buttons);
        label_112->setObjectName(QStringLiteral("label_112"));
        label_112->setGeometry(QRect(295, 0, 30, 20));
        label_112->setAlignment(Qt::AlignCenter);
        label_88 = new QLabel(Buttons);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(175, 0, 30, 20));
        label_88->setAlignment(Qt::AlignCenter);
        label_113 = new QLabel(Buttons);
        label_113->setObjectName(QStringLiteral("label_113"));
        label_113->setGeometry(QRect(295, 40, 30, 20));
        label_113->setAlignment(Qt::AlignCenter);
        label_83 = new QLabel(Buttons);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(135, 120, 30, 20));
        label_83->setAlignment(Qt::AlignCenter);
        label_137 = new QLabel(Buttons);
        label_137->setObjectName(QStringLiteral("label_137"));
        label_137->setGeometry(QRect(415, 40, 30, 20));
        label_137->setAlignment(Qt::AlignCenter);
        BUTTON_RG4 = new QPushButton(Buttons);
        BUTTON_RG4->setObjectName(QStringLiteral("BUTTON_RG4"));
        BUTTON_RG4->setGeometry(QRect(340, 180, 20, 20));
        label_96 = new QLabel(Buttons);
        label_96->setObjectName(QStringLiteral("label_96"));
        label_96->setGeometry(QRect(215, 0, 30, 20));
        label_96->setAlignment(Qt::AlignCenter);
        label_80 = new QLabel(Buttons);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(135, -1, 30, 20));
        label_80->setAlignment(Qt::AlignCenter);
        label_95 = new QLabel(Buttons);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(215, 240, 30, 20));
        label_95->setAlignment(Qt::AlignCenter);
        BUTTON_RJ3 = new QPushButton(Buttons);
        BUTTON_RJ3->setObjectName(QStringLiteral("BUTTON_RJ3"));
        BUTTON_RJ3->setGeometry(QRect(420, 140, 20, 20));
        BUTTON_RB4 = new QPushButton(Buttons);
        BUTTON_RB4->setObjectName(QStringLiteral("BUTTON_RB4"));
        BUTTON_RB4->setGeometry(QRect(140, 180, 20, 20));
        label_107 = new QLabel(Buttons);
        label_107->setObjectName(QStringLiteral("label_107"));
        label_107->setGeometry(QRect(255, 120, 30, 20));
        label_107->setAlignment(Qt::AlignCenter);
        label_133 = new QLabel(Buttons);
        label_133->setObjectName(QStringLiteral("label_133"));
        label_133->setGeometry(QRect(415, 160, 30, 20));
        label_133->setAlignment(Qt::AlignCenter);
        BUTTON_RF2 = new QPushButton(Buttons);
        BUTTON_RF2->setObjectName(QStringLiteral("BUTTON_RF2"));
        BUTTON_RF2->setGeometry(QRect(300, 100, 20, 20));
        BUTTON_RF3 = new QPushButton(Buttons);
        BUTTON_RF3->setObjectName(QStringLiteral("BUTTON_RF3"));
        BUTTON_RF3->setGeometry(QRect(300, 140, 20, 20));
        BUTTON_RC7 = new QPushButton(Buttons);
        BUTTON_RC7->setObjectName(QStringLiteral("BUTTON_RC7"));
        BUTTON_RC7->setGeometry(QRect(180, 300, 20, 20));
        label_85 = new QLabel(Buttons);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(175, 160, 30, 20));
        label_85->setAlignment(Qt::AlignCenter);
        BUTTON_RB5 = new QPushButton(Buttons);
        BUTTON_RB5->setObjectName(QStringLiteral("BUTTON_RB5"));
        BUTTON_RB5->setGeometry(QRect(140, 220, 20, 20));
        BUTTON_RF5 = new QPushButton(Buttons);
        BUTTON_RF5->setObjectName(QStringLiteral("BUTTON_RF5"));
        BUTTON_RF5->setGeometry(QRect(300, 220, 20, 20));
        label_70 = new QLabel(Buttons);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(95, 40, 30, 20));
        label_70->setAlignment(Qt::AlignCenter);
        label_71 = new QLabel(Buttons);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(95, 80, 30, 20));
        label_71->setAlignment(Qt::AlignCenter);
        label_125 = new QLabel(Buttons);
        label_125->setObjectName(QStringLiteral("label_125"));
        label_125->setGeometry(QRect(375, 160, 30, 20));
        label_125->setAlignment(Qt::AlignCenter);
        label_131 = new QLabel(Buttons);
        label_131->setObjectName(QStringLiteral("label_131"));
        label_131->setGeometry(QRect(375, 120, 30, 20));
        label_131->setAlignment(Qt::AlignCenter);
        label_124 = new QLabel(Buttons);
        label_124->setObjectName(QStringLiteral("label_124"));
        label_124->setGeometry(QRect(335, 280, 30, 20));
        label_124->setAlignment(Qt::AlignCenter);
        label_103 = new QLabel(Buttons);
        label_103->setObjectName(QStringLiteral("label_103"));
        label_103->setGeometry(QRect(255, 240, 30, 20));
        label_103->setAlignment(Qt::AlignCenter);
        BUTTON_RH2 = new QPushButton(Buttons);
        BUTTON_RH2->setObjectName(QStringLiteral("BUTTON_RH2"));
        BUTTON_RH2->setGeometry(QRect(380, 100, 20, 20));
        BUTTON_RD2 = new QPushButton(Buttons);
        BUTTON_RD2->setObjectName(QStringLiteral("BUTTON_RD2"));
        BUTTON_RD2->setGeometry(QRect(220, 100, 20, 20));
        label_118 = new QLabel(Buttons);
        label_118->setObjectName(QStringLiteral("label_118"));
        label_118->setGeometry(QRect(335, 80, 30, 20));
        label_118->setAlignment(Qt::AlignCenter);
        label_75 = new QLabel(Buttons);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(95, 200, 30, 20));
        label_75->setAlignment(Qt::AlignCenter);
        BUTTON_RH6 = new QPushButton(Buttons);
        BUTTON_RH6->setObjectName(QStringLiteral("BUTTON_RH6"));
        BUTTON_RH6->setGeometry(QRect(380, 260, 20, 20));
        label_115 = new QLabel(Buttons);
        label_115->setObjectName(QStringLiteral("label_115"));
        label_115->setGeometry(QRect(295, 120, 30, 20));
        label_115->setAlignment(Qt::AlignCenter);
        BUTTON_RE4 = new QPushButton(Buttons);
        BUTTON_RE4->setObjectName(QStringLiteral("BUTTON_RE4"));
        BUTTON_RE4->setGeometry(QRect(260, 180, 20, 20));
        label_117 = new QLabel(Buttons);
        label_117->setObjectName(QStringLiteral("label_117"));
        label_117->setGeometry(QRect(335, 160, 30, 20));
        label_117->setAlignment(Qt::AlignCenter);
        BUTTON_RC6 = new QPushButton(Buttons);
        BUTTON_RC6->setObjectName(QStringLiteral("BUTTON_RC6"));
        BUTTON_RC6->setGeometry(QRect(180, 260, 20, 20));
        BUTTON_RG2 = new QPushButton(Buttons);
        BUTTON_RG2->setObjectName(QStringLiteral("BUTTON_RG2"));
        BUTTON_RG2->setGeometry(QRect(340, 100, 20, 20));
        label_116 = new QLabel(Buttons);
        label_116->setObjectName(QStringLiteral("label_116"));
        label_116->setGeometry(QRect(295, 280, 30, 20));
        label_116->setAlignment(Qt::AlignCenter);
        label_126 = new QLabel(Buttons);
        label_126->setObjectName(QStringLiteral("label_126"));
        label_126->setGeometry(QRect(375, 80, 30, 20));
        label_126->setAlignment(Qt::AlignCenter);
        label_92 = new QLabel(Buttons);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(175, 280, 30, 20));
        label_92->setAlignment(Qt::AlignCenter);
        BUTTON_RF6 = new QPushButton(Buttons);
        BUTTON_RF6->setObjectName(QStringLiteral("BUTTON_RF6"));
        BUTTON_RF6->setGeometry(QRect(300, 260, 20, 20));
        label_138 = new QLabel(Buttons);
        label_138->setObjectName(QStringLiteral("label_138"));
        label_138->setGeometry(QRect(415, 200, 30, 20));
        label_138->setAlignment(Qt::AlignCenter);
        BUTTON_RF1 = new QPushButton(Buttons);
        BUTTON_RF1->setObjectName(QStringLiteral("BUTTON_RF1"));
        BUTTON_RF1->setGeometry(QRect(300, 60, 20, 20));
        label_36 = new QLabel(Buttons);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(95, 0, 30, 20));
        label_36->setAlignment(Qt::AlignCenter);
        BUTTON_RC5 = new QPushButton(Buttons);
        BUTTON_RC5->setObjectName(QStringLiteral("BUTTON_RC5"));
        BUTTON_RC5->setGeometry(QRect(180, 220, 20, 20));
        BUTTON_RB0 = new QPushButton(Buttons);
        BUTTON_RB0->setObjectName(QStringLiteral("BUTTON_RB0"));
        BUTTON_RB0->setGeometry(QRect(140, 20, 20, 20));
        BUTTON_RB0->setCursor(QCursor(Qt::PointingHandCursor));
        label_77 = new QLabel(Buttons);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(135, 160, 30, 20));
        label_77->setAlignment(Qt::AlignCenter);
        label_136 = new QLabel(Buttons);
        label_136->setObjectName(QStringLiteral("label_136"));
        label_136->setGeometry(QRect(415, 0, 30, 20));
        label_136->setAlignment(Qt::AlignCenter);
        label_139 = new QLabel(Buttons);
        label_139->setObjectName(QStringLiteral("label_139"));
        label_139->setGeometry(QRect(415, 120, 30, 20));
        label_139->setAlignment(Qt::AlignCenter);
        label_93 = new QLabel(Buttons);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(215, 160, 30, 20));
        label_93->setAlignment(Qt::AlignCenter);
        BUTTON_RB2 = new QPushButton(Buttons);
        BUTTON_RB2->setObjectName(QStringLiteral("BUTTON_RB2"));
        BUTTON_RB2->setGeometry(QRect(140, 100, 20, 20));
        label_123 = new QLabel(Buttons);
        label_123->setObjectName(QStringLiteral("label_123"));
        label_123->setGeometry(QRect(335, 120, 30, 20));
        label_123->setAlignment(Qt::AlignCenter);
        BUTTON_RE3 = new QPushButton(Buttons);
        BUTTON_RE3->setObjectName(QStringLiteral("BUTTON_RE3"));
        BUTTON_RE3->setGeometry(QRect(260, 140, 20, 20));
        BUTTON_RJ0 = new QPushButton(Buttons);
        BUTTON_RJ0->setObjectName(QStringLiteral("BUTTON_RJ0"));
        BUTTON_RJ0->setGeometry(QRect(420, 20, 20, 20));
        BUTTON_RJ0->setCursor(QCursor(Qt::PointingHandCursor));
        BUTTON_RD7 = new QPushButton(Buttons);
        BUTTON_RD7->setObjectName(QStringLiteral("BUTTON_RD7"));
        BUTTON_RD7->setGeometry(QRect(220, 300, 20, 20));
        BUTTON_RC0 = new QPushButton(Buttons);
        BUTTON_RC0->setObjectName(QStringLiteral("BUTTON_RC0"));
        BUTTON_RC0->setGeometry(QRect(180, 20, 20, 20));
        BUTTON_RC0->setCursor(QCursor(Qt::PointingHandCursor));
        BUTTON_RG0 = new QPushButton(Buttons);
        BUTTON_RG0->setObjectName(QStringLiteral("BUTTON_RG0"));
        BUTTON_RG0->setGeometry(QRect(340, 20, 20, 20));
        BUTTON_RG0->setCursor(QCursor(Qt::PointingHandCursor));
        label_76 = new QLabel(Buttons);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(95, 280, 30, 20));
        label_76->setAlignment(Qt::AlignCenter);
        BUTTON_RG5 = new QPushButton(Buttons);
        BUTTON_RG5->setObjectName(QStringLiteral("BUTTON_RG5"));
        BUTTON_RG5->setGeometry(QRect(340, 220, 20, 20));
        label_102 = new QLabel(Buttons);
        label_102->setObjectName(QStringLiteral("label_102"));
        label_102->setGeometry(QRect(255, 80, 30, 20));
        label_102->setAlignment(Qt::AlignCenter);
        label_81 = new QLabel(Buttons);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(135, 40, 30, 20));
        label_81->setAlignment(Qt::AlignCenter);
        BUTTON_RG3 = new QPushButton(Buttons);
        BUTTON_RG3->setObjectName(QStringLiteral("BUTTON_RG3"));
        BUTTON_RG3->setGeometry(QRect(340, 140, 20, 20));
        BUTTON_RH1 = new QPushButton(Buttons);
        BUTTON_RH1->setObjectName(QStringLiteral("BUTTON_RH1"));
        BUTTON_RH1->setGeometry(QRect(380, 60, 20, 20));
        label_110 = new QLabel(Buttons);
        label_110->setObjectName(QStringLiteral("label_110"));
        label_110->setGeometry(QRect(295, 80, 30, 20));
        label_110->setAlignment(Qt::AlignCenter);
        BUTTON_RJ7 = new QPushButton(Buttons);
        BUTTON_RJ7->setObjectName(QStringLiteral("BUTTON_RJ7"));
        BUTTON_RJ7->setGeometry(QRect(420, 300, 20, 20));
        label_130 = new QLabel(Buttons);
        label_130->setObjectName(QStringLiteral("label_130"));
        label_130->setGeometry(QRect(375, 200, 30, 20));
        label_130->setAlignment(Qt::AlignCenter);
        label_105 = new QLabel(Buttons);
        label_105->setObjectName(QStringLiteral("label_105"));
        label_105->setGeometry(QRect(255, 40, 30, 20));
        label_105->setAlignment(Qt::AlignCenter);
        label_89 = new QLabel(Buttons);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(175, 40, 30, 20));
        label_89->setAlignment(Qt::AlignCenter);
        BUTTON_RE2 = new QPushButton(Buttons);
        BUTTON_RE2->setObjectName(QStringLiteral("BUTTON_RE2"));
        BUTTON_RE2->setGeometry(QRect(260, 100, 20, 20));
        label_82 = new QLabel(Buttons);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(135, 200, 30, 20));
        label_82->setAlignment(Qt::AlignCenter);
        BUTTON_RH0 = new QPushButton(Buttons);
        BUTTON_RH0->setObjectName(QStringLiteral("BUTTON_RH0"));
        BUTTON_RH0->setGeometry(QRect(380, 20, 20, 20));
        BUTTON_RH0->setCursor(QCursor(Qt::PointingHandCursor));
        BUTTON_RB3 = new QPushButton(Buttons);
        BUTTON_RB3->setObjectName(QStringLiteral("BUTTON_RB3"));
        BUTTON_RB3->setGeometry(QRect(140, 140, 20, 20));
        BUTTON_RE6 = new QPushButton(Buttons);
        BUTTON_RE6->setObjectName(QStringLiteral("BUTTON_RE6"));
        BUTTON_RE6->setGeometry(QRect(260, 260, 20, 20));
        label_104 = new QLabel(Buttons);
        label_104->setObjectName(QStringLiteral("label_104"));
        label_104->setGeometry(QRect(255, 0, 30, 20));
        label_104->setAlignment(Qt::AlignCenter);
        BUTTON_RG6 = new QPushButton(Buttons);
        BUTTON_RG6->setObjectName(QStringLiteral("BUTTON_RG6"));
        BUTTON_RG6->setGeometry(QRect(340, 260, 20, 20));
        label_90 = new QLabel(Buttons);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(175, 200, 30, 20));
        label_90->setAlignment(Qt::AlignCenter);
        label_109 = new QLabel(Buttons);
        label_109->setObjectName(QStringLiteral("label_109"));
        label_109->setGeometry(QRect(295, 160, 30, 20));
        label_109->setAlignment(Qt::AlignCenter);
        BUTTON_RC4 = new QPushButton(Buttons);
        BUTTON_RC4->setObjectName(QStringLiteral("BUTTON_RC4"));
        BUTTON_RC4->setGeometry(QRect(180, 180, 20, 20));
        label_119 = new QLabel(Buttons);
        label_119->setObjectName(QStringLiteral("label_119"));
        label_119->setGeometry(QRect(335, 240, 30, 20));
        label_119->setAlignment(Qt::AlignCenter);
        label_135 = new QLabel(Buttons);
        label_135->setObjectName(QStringLiteral("label_135"));
        label_135->setGeometry(QRect(415, 240, 30, 20));
        label_135->setAlignment(Qt::AlignCenter);
        label_79 = new QLabel(Buttons);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(135, 240, 30, 20));
        label_79->setAlignment(Qt::AlignCenter);
        BUTTON_RB7 = new QPushButton(Buttons);
        BUTTON_RB7->setObjectName(QStringLiteral("BUTTON_RB7"));
        BUTTON_RB7->setGeometry(QRect(140, 300, 20, 20));
        BUTTON_RB6 = new QPushButton(Buttons);
        BUTTON_RB6->setObjectName(QStringLiteral("BUTTON_RB6"));
        BUTTON_RB6->setGeometry(QRect(140, 260, 20, 20));
        BUTTON_RE1 = new QPushButton(Buttons);
        BUTTON_RE1->setObjectName(QStringLiteral("BUTTON_RE1"));
        BUTTON_RE1->setGeometry(QRect(260, 60, 20, 20));
        label_134 = new QLabel(Buttons);
        label_134->setObjectName(QStringLiteral("label_134"));
        label_134->setGeometry(QRect(415, 80, 30, 20));
        label_134->setAlignment(Qt::AlignCenter);
        BUTTON_RA5 = new QPushButton(Buttons);
        BUTTON_RA5->setObjectName(QStringLiteral("BUTTON_RA5"));
        BUTTON_RA5->setGeometry(QRect(100, 220, 20, 20));
        BUTTON_RF0 = new QPushButton(Buttons);
        BUTTON_RF0->setObjectName(QStringLiteral("BUTTON_RF0"));
        BUTTON_RF0->setGeometry(QRect(300, 20, 20, 20));
        BUTTON_RF0->setCursor(QCursor(Qt::PointingHandCursor));
        label_72 = new QLabel(Buttons);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(95, 120, 30, 20));
        label_72->setAlignment(Qt::AlignCenter);
        label_127 = new QLabel(Buttons);
        label_127->setObjectName(QStringLiteral("label_127"));
        label_127->setGeometry(QRect(375, 240, 30, 20));
        label_127->setAlignment(Qt::AlignCenter);
        label_94 = new QLabel(Buttons);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(215, 80, 30, 20));
        label_94->setAlignment(Qt::AlignCenter);
        BUTTON_RA4 = new QPushButton(Buttons);
        BUTTON_RA4->setObjectName(QStringLiteral("BUTTON_RA4"));
        BUTTON_RA4->setGeometry(QRect(100, 180, 20, 20));
        label_74 = new QLabel(Buttons);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(95, 160, 30, 20));
        label_74->setAlignment(Qt::AlignCenter);
        label_84 = new QLabel(Buttons);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(135, 280, 30, 20));
        label_84->setAlignment(Qt::AlignCenter);
        BUTTON_RF7 = new QPushButton(Buttons);
        BUTTON_RF7->setObjectName(QStringLiteral("BUTTON_RF7"));
        BUTTON_RF7->setGeometry(QRect(300, 300, 20, 20));
        label_97 = new QLabel(Buttons);
        label_97->setObjectName(QStringLiteral("label_97"));
        label_97->setGeometry(QRect(215, 40, 30, 20));
        label_97->setAlignment(Qt::AlignCenter);
        BUTTON_RC1 = new QPushButton(Buttons);
        BUTTON_RC1->setObjectName(QStringLiteral("BUTTON_RC1"));
        BUTTON_RC1->setGeometry(QRect(180, 60, 20, 20));
        BUTTON_RJ2 = new QPushButton(Buttons);
        BUTTON_RJ2->setObjectName(QStringLiteral("BUTTON_RJ2"));
        BUTTON_RJ2->setGeometry(QRect(420, 100, 20, 20));
        BUTTON_RD1 = new QPushButton(Buttons);
        BUTTON_RD1->setObjectName(QStringLiteral("BUTTON_RD1"));
        BUTTON_RD1->setGeometry(QRect(220, 60, 20, 20));
        label_87 = new QLabel(Buttons);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(175, 240, 30, 20));
        label_87->setAlignment(Qt::AlignCenter);
        label_114 = new QLabel(Buttons);
        label_114->setObjectName(QStringLiteral("label_114"));
        label_114->setGeometry(QRect(295, 200, 30, 20));
        label_114->setAlignment(Qt::AlignCenter);
        BUTTON_RD0 = new QPushButton(Buttons);
        BUTTON_RD0->setObjectName(QStringLiteral("BUTTON_RD0"));
        BUTTON_RD0->setGeometry(QRect(220, 20, 20, 20));
        BUTTON_RD0->setCursor(QCursor(Qt::PointingHandCursor));
        label_78 = new QLabel(Buttons);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(135, 80, 30, 20));
        label_78->setAlignment(Qt::AlignCenter);
        BUTTON_RH7 = new QPushButton(Buttons);
        BUTTON_RH7->setObjectName(QStringLiteral("BUTTON_RH7"));
        BUTTON_RH7->setGeometry(QRect(380, 300, 20, 20));
        BUTTON_RD3 = new QPushButton(Buttons);
        BUTTON_RD3->setObjectName(QStringLiteral("BUTTON_RD3"));
        BUTTON_RD3->setGeometry(QRect(220, 140, 20, 20));
        label_111 = new QLabel(Buttons);
        label_111->setObjectName(QStringLiteral("label_111"));
        label_111->setGeometry(QRect(295, 240, 30, 20));
        label_111->setAlignment(Qt::AlignCenter);
        BUTTON_RE5 = new QPushButton(Buttons);
        BUTTON_RE5->setObjectName(QStringLiteral("BUTTON_RE5"));
        BUTTON_RE5->setGeometry(QRect(260, 220, 20, 20));
        label_129 = new QLabel(Buttons);
        label_129->setObjectName(QStringLiteral("label_129"));
        label_129->setGeometry(QRect(375, 40, 30, 20));
        label_129->setAlignment(Qt::AlignCenter);
        label_128 = new QLabel(Buttons);
        label_128->setObjectName(QStringLiteral("label_128"));
        label_128->setGeometry(QRect(375, 0, 30, 20));
        label_128->setAlignment(Qt::AlignCenter);
        BUTTON_RF4 = new QPushButton(Buttons);
        BUTTON_RF4->setObjectName(QStringLiteral("BUTTON_RF4"));
        BUTTON_RF4->setGeometry(QRect(300, 180, 20, 20));
        BUTTON_RB1 = new QPushButton(Buttons);
        BUTTON_RB1->setObjectName(QStringLiteral("BUTTON_RB1"));
        BUTTON_RB1->setGeometry(QRect(140, 60, 20, 20));
        label_120 = new QLabel(Buttons);
        label_120->setObjectName(QStringLiteral("label_120"));
        label_120->setGeometry(QRect(335, 0, 30, 20));
        label_120->setAlignment(Qt::AlignCenter);
        BUTTON_RA6 = new QPushButton(Buttons);
        BUTTON_RA6->setObjectName(QStringLiteral("BUTTON_RA6"));
        BUTTON_RA6->setGeometry(QRect(100, 260, 20, 20));
        label_99 = new QLabel(Buttons);
        label_99->setObjectName(QStringLiteral("label_99"));
        label_99->setGeometry(QRect(215, 120, 30, 20));
        label_99->setAlignment(Qt::AlignCenter);
        label_140 = new QLabel(Buttons);
        label_140->setObjectName(QStringLiteral("label_140"));
        label_140->setGeometry(QRect(415, 280, 30, 20));
        label_140->setAlignment(Qt::AlignCenter);
        label_121 = new QLabel(Buttons);
        label_121->setObjectName(QStringLiteral("label_121"));
        label_121->setGeometry(QRect(335, 40, 30, 20));
        label_121->setAlignment(Qt::AlignCenter);
        BUTTON_RD4 = new QPushButton(Buttons);
        BUTTON_RD4->setObjectName(QStringLiteral("BUTTON_RD4"));
        BUTTON_RD4->setGeometry(QRect(220, 180, 20, 20));
        J10 = new RadioButtons(Buttons);
        J10->setObjectName(QStringLiteral("J10"));
        J10->setGeometry(QRect(10, 230, 70, 65));

        retranslateUi(Buttons);

        QMetaObject::connectSlotsByName(Buttons);
    } // setupUi

    void retranslateUi(QWidget *Buttons)
    {
        Buttons->setWindowTitle(QApplication::translate("Buttons", "Form", 0));
        BUTTON_RD5->setText(QString());
        label_73->setText(QApplication::translate("Buttons", "RA6", 0));
        BUTTON_RC3->setText(QString());
        label_132->setText(QApplication::translate("Buttons", "RH7", 0));
        BUTTON_RG1->setText(QString());
        label_100->setText(QApplication::translate("Buttons", "RD7", 0));
        label_122->setText(QApplication::translate("Buttons", "RG5", 0));
        label_108->setText(QApplication::translate("Buttons", "RE7", 0));
        BUTTON_RE0->setText(QString());
        label_98->setText(QApplication::translate("Buttons", "RD5", 0));
        label_106->setText(QApplication::translate("Buttons", "RE5", 0));
        BUTTON_RH4->setText(QString());
        BUTTON_RH3->setText(QString());
        BUTTON_RC2->setText(QString());
        BUTTON_RE7->setText(QString());
        BUTTON_RA1->setText(QString());
        BUTTON_RH5->setText(QString());
        BUTTON_RJ4->setText(QString());
        label_101->setText(QApplication::translate("Buttons", "RE4", 0));
        BUTTON_RG7->setText(QString());
        BUTTON_RA3->setText(QString());
        BUTTON_RD6->setText(QString());
        label_91->setText(QApplication::translate("Buttons", "RC3", 0));
        BUTTON_RJ6->setText(QString());
        BUTTON_RA7->setText(QString());
        label_86->setText(QApplication::translate("Buttons", "RC2", 0));
        BUTTON_RJ1->setText(QString());
        BUTTON_RA2->setText(QString());
        BUTTON_RA0->setText(QString());
        BUTTON_RJ5->setText(QString());
        label_112->setText(QApplication::translate("Buttons", "RF0", 0));
        label_88->setText(QApplication::translate("Buttons", "RC0", 0));
        label_113->setText(QApplication::translate("Buttons", "RF1", 0));
        label_83->setText(QApplication::translate("Buttons", "RB3", 0));
        label_137->setText(QApplication::translate("Buttons", "RJ1", 0));
        BUTTON_RG4->setText(QString());
        label_96->setText(QApplication::translate("Buttons", "RD0", 0));
        label_80->setText(QApplication::translate("Buttons", "RB0", 0));
        label_95->setText(QApplication::translate("Buttons", "RD6", 0));
        BUTTON_RJ3->setText(QString());
        BUTTON_RB4->setText(QString());
        label_107->setText(QApplication::translate("Buttons", "RE3", 0));
        label_133->setText(QApplication::translate("Buttons", "RJ4", 0));
        BUTTON_RF2->setText(QString());
        BUTTON_RF3->setText(QString());
        BUTTON_RC7->setText(QString());
        label_85->setText(QApplication::translate("Buttons", "RC4", 0));
        BUTTON_RB5->setText(QString());
        BUTTON_RF5->setText(QString());
        label_70->setText(QApplication::translate("Buttons", "RA1", 0));
        label_71->setText(QApplication::translate("Buttons", "RA2", 0));
        label_125->setText(QApplication::translate("Buttons", "RH4", 0));
        label_131->setText(QApplication::translate("Buttons", "RH3", 0));
        label_124->setText(QApplication::translate("Buttons", "RG7", 0));
        label_103->setText(QApplication::translate("Buttons", "RE6", 0));
        BUTTON_RH2->setText(QString());
        BUTTON_RD2->setText(QString());
        label_118->setText(QApplication::translate("Buttons", "RG2", 0));
        label_75->setText(QApplication::translate("Buttons", "RA5", 0));
        BUTTON_RH6->setText(QString());
        label_115->setText(QApplication::translate("Buttons", "RF3", 0));
        BUTTON_RE4->setText(QString());
        label_117->setText(QApplication::translate("Buttons", "RG4", 0));
        BUTTON_RC6->setText(QString());
        BUTTON_RG2->setText(QString());
        label_116->setText(QApplication::translate("Buttons", "RF7", 0));
        label_126->setText(QApplication::translate("Buttons", "RH2", 0));
        label_92->setText(QApplication::translate("Buttons", "RC7", 0));
        BUTTON_RF6->setText(QString());
        label_138->setText(QApplication::translate("Buttons", "RJ5", 0));
        BUTTON_RF1->setText(QString());
        label_36->setText(QApplication::translate("Buttons", "RA0", 0));
        BUTTON_RC5->setText(QString());
        BUTTON_RB0->setText(QString());
        label_77->setText(QApplication::translate("Buttons", "RB4", 0));
        label_136->setText(QApplication::translate("Buttons", "RJ0", 0));
        label_139->setText(QApplication::translate("Buttons", "RJ3", 0));
        label_93->setText(QApplication::translate("Buttons", "RD4", 0));
        BUTTON_RB2->setText(QString());
        label_123->setText(QApplication::translate("Buttons", "RG3", 0));
        BUTTON_RE3->setText(QString());
        BUTTON_RJ0->setText(QString());
        BUTTON_RD7->setText(QString());
        BUTTON_RC0->setText(QString());
        BUTTON_RG0->setText(QString());
        label_76->setText(QApplication::translate("Buttons", "RA7", 0));
        BUTTON_RG5->setText(QString());
        label_102->setText(QApplication::translate("Buttons", "RE2", 0));
        label_81->setText(QApplication::translate("Buttons", "RB1", 0));
        BUTTON_RG3->setText(QString());
        BUTTON_RH1->setText(QString());
        label_110->setText(QApplication::translate("Buttons", "RF2", 0));
        BUTTON_RJ7->setText(QString());
        label_130->setText(QApplication::translate("Buttons", "RH5", 0));
        label_105->setText(QApplication::translate("Buttons", "RE1", 0));
        label_89->setText(QApplication::translate("Buttons", "RC1", 0));
        BUTTON_RE2->setText(QString());
        label_82->setText(QApplication::translate("Buttons", "RB5", 0));
        BUTTON_RH0->setText(QString());
        BUTTON_RB3->setText(QString());
        BUTTON_RE6->setText(QString());
        label_104->setText(QApplication::translate("Buttons", "RE0", 0));
        BUTTON_RG6->setText(QString());
        label_90->setText(QApplication::translate("Buttons", "RC5", 0));
        label_109->setText(QApplication::translate("Buttons", "RF4", 0));
        BUTTON_RC4->setText(QString());
        label_119->setText(QApplication::translate("Buttons", "RG6", 0));
        label_135->setText(QApplication::translate("Buttons", "RJ6", 0));
        label_79->setText(QApplication::translate("Buttons", "RB6", 0));
        BUTTON_RB7->setText(QString());
        BUTTON_RB6->setText(QString());
        BUTTON_RE1->setText(QString());
        label_134->setText(QApplication::translate("Buttons", "RJ2", 0));
        BUTTON_RA5->setText(QString());
        BUTTON_RF0->setText(QString());
        label_72->setText(QApplication::translate("Buttons", "RA3", 0));
        label_127->setText(QApplication::translate("Buttons", "RH6", 0));
        label_94->setText(QApplication::translate("Buttons", "RD2", 0));
        BUTTON_RA4->setText(QString());
        label_74->setText(QApplication::translate("Buttons", "RA4", 0));
        label_84->setText(QApplication::translate("Buttons", "RB7", 0));
        BUTTON_RF7->setText(QString());
        label_97->setText(QApplication::translate("Buttons", "RD1", 0));
        BUTTON_RC1->setText(QString());
        BUTTON_RJ2->setText(QString());
        BUTTON_RD1->setText(QString());
        label_87->setText(QApplication::translate("Buttons", "RC6", 0));
        label_114->setText(QApplication::translate("Buttons", "RF5", 0));
        BUTTON_RD0->setText(QString());
        label_78->setText(QApplication::translate("Buttons", "RB2", 0));
        BUTTON_RH7->setText(QString());
        BUTTON_RD3->setText(QString());
        label_111->setText(QApplication::translate("Buttons", "RF6", 0));
        BUTTON_RE5->setText(QString());
        label_129->setText(QApplication::translate("Buttons", "RH1", 0));
        label_128->setText(QApplication::translate("Buttons", "RH0", 0));
        BUTTON_RF4->setText(QString());
        BUTTON_RB1->setText(QString());
        label_120->setText(QApplication::translate("Buttons", "RG0", 0));
        BUTTON_RA6->setText(QString());
        label_99->setText(QApplication::translate("Buttons", "RD3", 0));
        label_140->setText(QApplication::translate("Buttons", "RJ7", 0));
        label_121->setText(QApplication::translate("Buttons", "RG1", 0));
        BUTTON_RD4->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Buttons: public Ui_Buttons {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BUTTONS_H
