/********************************************************************************
** Form generated from reading UI file 'diodes.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIODES_H
#define UI_DIODES_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Diodes
{
public:
    QLabel *label_155;
    QLabel *DIODE_RJ0;
    QLabel *DIODE_RE0;
    QLabel *DIODE_RB6;
    QLabel *label_161;
    QLabel *label_248;
    QLabel *DIODE_RA2;
    QLabel *label_213;
    QLabel *label_147;
    QLabel *DIODE_RJ5;
    QLabel *DIODE_RH4;
    QLabel *label_252;
    QLabel *DIODE_RG2;
    QLabel *label_240;
    QLabel *DIODE_RA5;
    QLabel *DIODE_RD1;
    QLabel *DIODE_RG7;
    QLabel *label_221;
    QLabel *DIODE_RJ7;
    QLabel *label_209;
    QLabel *label_265;
    QLabel *label_217;
    QLabel *label_201;
    QLabel *DIODE_RH2;
    QLabel *label_256;
    QLabel *DIODE_RE1;
    QLabel *DIODE_RJ1;
    QLabel *DIODE_RC1;
    QLabel *DIODE_RH7;
    QLabel *label_160;
    QLabel *label_185;
    QLabel *DIODE_RG5;
    QLabel *label_204;
    QLabel *label_268;
    QLabel *label_189;
    QLabel *DIODE_RE2;
    QLabel *DIODE_RJ3;
    QLabel *label_257;
    QLabel *DIODE_RG3;
    QLabel *DIODE_RA3;
    QLabel *label_173;
    QLabel *DIODE_RF7;
    QLabel *label_149;
    QLabel *label_277;
    QLabel *DIODE_RE4;
    QLabel *DIODE_RB4;
    QLabel *label_225;
    QLabel *DIODE_RC3;
    QLabel *label_269;
    QLabel *label_279;
    QLabel *label_208;
    QLabel *DIODE_RH6;
    QLabel *DIODE_RH5;
    QLabel *DIODE_RC6;
    QLabel *label_183;
    QLabel *label_167;
    QLabel *DIODE_RE3;
    QLabel *DIODE_RC7;
    QLabel *label_284;
    QLabel *DIODE_RA7;
    QLabel *DIODE_RD0;
    QLabel *label_144;
    QLabel *label_192;
    QLabel *DIODE_RA4;
    QLabel *DIODE_RF6;
    QLabel *DIODE_RC2;
    QLabel *DIODE_RH0;
    QLabel *label_153;
    QLabel *DIODE_RF4;
    QLabel *label_216;
    QLabel *label_193;
    QLabel *DIODE_RC4;
    QLabel *DIODE_RB3;
    QLabel *label_261;
    QLabel *DIODE_RJ4;
    QLabel *DIODE_RB7;
    QLabel *label_205;
    QLabel *DIODE_RF5;
    QLabel *label_264;
    QLabel *DIODE_RA6;
    QLabel *label_231;
    QLabel *DIODE_RF3;
    QLabel *DIODE_RB0;
    QLabel *DIODE_RD2;
    QLabel *label_157;
    QLabel *label_241;
    QLabel *DIODE_RB5;
    QLabel *label_220;
    QLabel *label_151;
    QLabel *DIODE_RD4;
    QLabel *DIODE_RD5;
    QLabel *label_197;
    QLabel *DIODE_RH3;
    QLabel *DIODE_RD6;
    QLabel *DIODE_RE7;
    QLabel *label_249;
    QLabel *DIODE_RF0;
    QLabel *label_184;
    QLabel *label_232;
    QLabel *label_176;
    QLabel *DIODE_RE6;
    QLabel *label_215;
    QLabel *label_280;
    QLabel *label_177;
    QLabel *DIODE_RB1;
    QLabel *DIODE_RJ6;
    QLabel *DIODE_RG6;
    QLabel *label_168;
    QLabel *label_229;
    QLabel *label_165;
    QLabel *DIODE_RC0;
    QLabel *label_237;
    QLabel *label_247;
    QLabel *label_181;
    QLabel *label_199;
    QLabel *label_281;
    QLabel *DIODE_RG1;
    QLabel *DIODE_RD3;
    QLabel *DIODE_RF2;
    QLabel *label_224;
    QLabel *DIODE_RA1;
    QLabel *label_172;
    QLabel *label_233;
    QLabel *label_188;
    QLabel *label_169;
    QLabel *DIODE_RG0;
    QLabel *label_253;
    QLabel *DIODE_RE5;
    QLabel *DIODE_RB2;
    QLabel *label_263;
    QLabel *DIODE_RA0;
    QLabel *label_285;
    QLabel *label_236;
    QLabel *label_272;
    QLabel *DIODE_RH1;
    QLabel *DIODE_RG4;
    QLabel *DIODE_RC5;
    QLabel *DIODE_RD7;
    QLabel *DIODE_RF1;
    QLabel *label_200;
    QLabel *label_145;
    QLabel *label_273;
    QLabel *DIODE_RJ2;
    QLabel *label_245;

    void setupUi(QWidget *Diodes)
    {
        if (Diodes->objectName().isEmpty())
            Diodes->setObjectName(QStringLiteral("Diodes"));
        Diodes->resize(350, 320);
        label_155 = new QLabel(Diodes);
        label_155->setObjectName(QStringLiteral("label_155"));
        label_155->setGeometry(QRect(0, 60, 30, 20));
        DIODE_RJ0 = new QLabel(Diodes);
        DIODE_RJ0->setObjectName(QStringLiteral("DIODE_RJ0"));
        DIODE_RJ0->setGeometry(QRect(320, -30, 30, 50));
        DIODE_RJ0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ0->setScaledContents(false);
        DIODE_RJ0->setAlignment(Qt::AlignCenter);
        DIODE_RE0 = new QLabel(Diodes);
        DIODE_RE0->setObjectName(QStringLiteral("DIODE_RE0"));
        DIODE_RE0->setGeometry(QRect(160, -30, 30, 50));
        DIODE_RE0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE0->setScaledContents(false);
        DIODE_RE0->setAlignment(Qt::AlignCenter);
        DIODE_RB6 = new QLabel(Diodes);
        DIODE_RB6->setObjectName(QStringLiteral("DIODE_RB6"));
        DIODE_RB6->setGeometry(QRect(40, 210, 30, 50));
        DIODE_RB6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB6->setScaledContents(false);
        DIODE_RB6->setAlignment(Qt::AlignCenter);
        label_161 = new QLabel(Diodes);
        label_161->setObjectName(QStringLiteral("label_161"));
        label_161->setGeometry(QRect(40, 300, 30, 20));
        label_248 = new QLabel(Diodes);
        label_248->setObjectName(QStringLiteral("label_248"));
        label_248->setGeometry(QRect(240, 220, 30, 20));
        DIODE_RA2 = new QLabel(Diodes);
        DIODE_RA2->setObjectName(QStringLiteral("DIODE_RA2"));
        DIODE_RA2->setGeometry(QRect(0, 50, 30, 50));
        DIODE_RA2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA2->setScaledContents(false);
        DIODE_RA2->setAlignment(Qt::AlignCenter);
        label_213 = new QLabel(Diodes);
        label_213->setObjectName(QStringLiteral("label_213"));
        label_213->setGeometry(QRect(160, 60, 30, 20));
        label_147 = new QLabel(Diodes);
        label_147->setObjectName(QStringLiteral("label_147"));
        label_147->setGeometry(QRect(0, 220, 30, 20));
        DIODE_RJ5 = new QLabel(Diodes);
        DIODE_RJ5->setObjectName(QStringLiteral("DIODE_RJ5"));
        DIODE_RJ5->setGeometry(QRect(320, 170, 30, 50));
        DIODE_RJ5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ5->setScaledContents(false);
        DIODE_RJ5->setAlignment(Qt::AlignCenter);
        DIODE_RH4 = new QLabel(Diodes);
        DIODE_RH4->setObjectName(QStringLiteral("DIODE_RH4"));
        DIODE_RH4->setGeometry(QRect(280, 130, 30, 50));
        DIODE_RH4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH4->setScaledContents(false);
        DIODE_RH4->setAlignment(Qt::AlignCenter);
        label_252 = new QLabel(Diodes);
        label_252->setObjectName(QStringLiteral("label_252"));
        label_252->setGeometry(QRect(240, 20, 30, 20));
        DIODE_RG2 = new QLabel(Diodes);
        DIODE_RG2->setObjectName(QStringLiteral("DIODE_RG2"));
        DIODE_RG2->setGeometry(QRect(240, 50, 30, 50));
        DIODE_RG2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG2->setScaledContents(false);
        DIODE_RG2->setAlignment(Qt::AlignCenter);
        label_240 = new QLabel(Diodes);
        label_240->setObjectName(QStringLiteral("label_240"));
        label_240->setGeometry(QRect(240, 140, 30, 20));
        DIODE_RA5 = new QLabel(Diodes);
        DIODE_RA5->setObjectName(QStringLiteral("DIODE_RA5"));
        DIODE_RA5->setGeometry(QRect(0, 170, 30, 50));
        DIODE_RA5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA5->setScaledContents(false);
        DIODE_RA5->setAlignment(Qt::AlignCenter);
        DIODE_RD1 = new QLabel(Diodes);
        DIODE_RD1->setObjectName(QStringLiteral("DIODE_RD1"));
        DIODE_RD1->setGeometry(QRect(120, 10, 30, 50));
        DIODE_RD1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD1->setScaledContents(false);
        DIODE_RD1->setAlignment(Qt::AlignCenter);
        DIODE_RG7 = new QLabel(Diodes);
        DIODE_RG7->setObjectName(QStringLiteral("DIODE_RG7"));
        DIODE_RG7->setGeometry(QRect(240, 250, 30, 50));
        DIODE_RG7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG7->setScaledContents(false);
        DIODE_RG7->setAlignment(Qt::AlignCenter);
        label_221 = new QLabel(Diodes);
        label_221->setObjectName(QStringLiteral("label_221"));
        label_221->setGeometry(QRect(160, 260, 30, 20));
        DIODE_RJ7 = new QLabel(Diodes);
        DIODE_RJ7->setObjectName(QStringLiteral("DIODE_RJ7"));
        DIODE_RJ7->setGeometry(QRect(320, 250, 30, 50));
        DIODE_RJ7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ7->setScaledContents(false);
        DIODE_RJ7->setAlignment(Qt::AlignCenter);
        label_209 = new QLabel(Diodes);
        label_209->setObjectName(QStringLiteral("label_209"));
        label_209->setGeometry(QRect(160, 300, 30, 20));
        label_265 = new QLabel(Diodes);
        label_265->setObjectName(QStringLiteral("label_265"));
        label_265->setGeometry(QRect(280, 100, 30, 20));
        label_217 = new QLabel(Diodes);
        label_217->setObjectName(QStringLiteral("label_217"));
        label_217->setGeometry(QRect(160, 100, 30, 20));
        label_201 = new QLabel(Diodes);
        label_201->setObjectName(QStringLiteral("label_201"));
        label_201->setGeometry(QRect(120, 100, 30, 20));
        DIODE_RH2 = new QLabel(Diodes);
        DIODE_RH2->setObjectName(QStringLiteral("DIODE_RH2"));
        DIODE_RH2->setGeometry(QRect(280, 50, 30, 50));
        DIODE_RH2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH2->setScaledContents(false);
        DIODE_RH2->setAlignment(Qt::AlignCenter);
        label_256 = new QLabel(Diodes);
        label_256->setObjectName(QStringLiteral("label_256"));
        label_256->setGeometry(QRect(280, 140, 30, 20));
        DIODE_RE1 = new QLabel(Diodes);
        DIODE_RE1->setObjectName(QStringLiteral("DIODE_RE1"));
        DIODE_RE1->setGeometry(QRect(160, 10, 30, 50));
        DIODE_RE1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE1->setScaledContents(false);
        DIODE_RE1->setAlignment(Qt::AlignCenter);
        DIODE_RJ1 = new QLabel(Diodes);
        DIODE_RJ1->setObjectName(QStringLiteral("DIODE_RJ1"));
        DIODE_RJ1->setGeometry(QRect(320, 10, 30, 50));
        DIODE_RJ1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ1->setScaledContents(false);
        DIODE_RJ1->setAlignment(Qt::AlignCenter);
        DIODE_RC1 = new QLabel(Diodes);
        DIODE_RC1->setObjectName(QStringLiteral("DIODE_RC1"));
        DIODE_RC1->setGeometry(QRect(80, 10, 30, 50));
        DIODE_RC1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC1->setScaledContents(false);
        DIODE_RC1->setAlignment(Qt::AlignCenter);
        DIODE_RH7 = new QLabel(Diodes);
        DIODE_RH7->setObjectName(QStringLiteral("DIODE_RH7"));
        DIODE_RH7->setGeometry(QRect(280, 250, 30, 50));
        DIODE_RH7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH7->setScaledContents(false);
        DIODE_RH7->setAlignment(Qt::AlignCenter);
        label_160 = new QLabel(Diodes);
        label_160->setObjectName(QStringLiteral("label_160"));
        label_160->setGeometry(QRect(40, 140, 30, 20));
        label_185 = new QLabel(Diodes);
        label_185->setObjectName(QStringLiteral("label_185"));
        label_185->setGeometry(QRect(80, 100, 30, 20));
        DIODE_RG5 = new QLabel(Diodes);
        DIODE_RG5->setObjectName(QStringLiteral("DIODE_RG5"));
        DIODE_RG5->setGeometry(QRect(240, 170, 30, 50));
        DIODE_RG5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG5->setScaledContents(false);
        DIODE_RG5->setAlignment(Qt::AlignCenter);
        label_204 = new QLabel(Diodes);
        label_204->setObjectName(QStringLiteral("label_204"));
        label_204->setGeometry(QRect(120, 20, 30, 20));
        label_268 = new QLabel(Diodes);
        label_268->setObjectName(QStringLiteral("label_268"));
        label_268->setGeometry(QRect(280, 20, 30, 20));
        label_189 = new QLabel(Diodes);
        label_189->setObjectName(QStringLiteral("label_189"));
        label_189->setGeometry(QRect(80, 260, 30, 20));
        DIODE_RE2 = new QLabel(Diodes);
        DIODE_RE2->setObjectName(QStringLiteral("DIODE_RE2"));
        DIODE_RE2->setGeometry(QRect(160, 50, 30, 50));
        DIODE_RE2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE2->setScaledContents(false);
        DIODE_RE2->setAlignment(Qt::AlignCenter);
        DIODE_RJ3 = new QLabel(Diodes);
        DIODE_RJ3->setObjectName(QStringLiteral("DIODE_RJ3"));
        DIODE_RJ3->setGeometry(QRect(320, 90, 30, 50));
        DIODE_RJ3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ3->setScaledContents(false);
        DIODE_RJ3->setAlignment(Qt::AlignCenter);
        label_257 = new QLabel(Diodes);
        label_257->setObjectName(QStringLiteral("label_257"));
        label_257->setGeometry(QRect(280, 300, 30, 20));
        DIODE_RG3 = new QLabel(Diodes);
        DIODE_RG3->setObjectName(QStringLiteral("DIODE_RG3"));
        DIODE_RG3->setGeometry(QRect(240, 90, 30, 50));
        DIODE_RG3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG3->setScaledContents(false);
        DIODE_RG3->setAlignment(Qt::AlignCenter);
        DIODE_RA3 = new QLabel(Diodes);
        DIODE_RA3->setObjectName(QStringLiteral("DIODE_RA3"));
        DIODE_RA3->setGeometry(QRect(0, 90, 30, 50));
        DIODE_RA3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA3->setScaledContents(false);
        DIODE_RA3->setAlignment(Qt::AlignCenter);
        label_173 = new QLabel(Diodes);
        label_173->setObjectName(QStringLiteral("label_173"));
        label_173->setGeometry(QRect(40, 260, 30, 20));
        DIODE_RF7 = new QLabel(Diodes);
        DIODE_RF7->setObjectName(QStringLiteral("DIODE_RF7"));
        DIODE_RF7->setGeometry(QRect(200, 250, 30, 50));
        DIODE_RF7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF7->setScaledContents(false);
        DIODE_RF7->setAlignment(Qt::AlignCenter);
        label_149 = new QLabel(Diodes);
        label_149->setObjectName(QStringLiteral("label_149"));
        label_149->setGeometry(QRect(0, 180, 30, 20));
        label_277 = new QLabel(Diodes);
        label_277->setObjectName(QStringLiteral("label_277"));
        label_277->setGeometry(QRect(320, 60, 30, 20));
        DIODE_RE4 = new QLabel(Diodes);
        DIODE_RE4->setObjectName(QStringLiteral("DIODE_RE4"));
        DIODE_RE4->setGeometry(QRect(160, 130, 30, 50));
        DIODE_RE4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE4->setScaledContents(false);
        DIODE_RE4->setAlignment(Qt::AlignCenter);
        DIODE_RB4 = new QLabel(Diodes);
        DIODE_RB4->setObjectName(QStringLiteral("DIODE_RB4"));
        DIODE_RB4->setGeometry(QRect(40, 130, 30, 50));
        DIODE_RB4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB4->setScaledContents(false);
        DIODE_RB4->setAlignment(Qt::AlignCenter);
        label_225 = new QLabel(Diodes);
        label_225->setObjectName(QStringLiteral("label_225"));
        label_225->setGeometry(QRect(200, 300, 30, 20));
        DIODE_RC3 = new QLabel(Diodes);
        DIODE_RC3->setObjectName(QStringLiteral("DIODE_RC3"));
        DIODE_RC3->setGeometry(QRect(80, 90, 30, 50));
        DIODE_RC3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC3->setScaledContents(false);
        DIODE_RC3->setAlignment(Qt::AlignCenter);
        label_269 = new QLabel(Diodes);
        label_269->setObjectName(QStringLiteral("label_269"));
        label_269->setGeometry(QRect(280, 260, 30, 20));
        label_279 = new QLabel(Diodes);
        label_279->setObjectName(QStringLiteral("label_279"));
        label_279->setGeometry(QRect(320, 180, 30, 20));
        label_208 = new QLabel(Diodes);
        label_208->setObjectName(QStringLiteral("label_208"));
        label_208->setGeometry(QRect(160, 140, 30, 20));
        DIODE_RH6 = new QLabel(Diodes);
        DIODE_RH6->setObjectName(QStringLiteral("DIODE_RH6"));
        DIODE_RH6->setGeometry(QRect(280, 210, 30, 50));
        DIODE_RH6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH6->setScaledContents(false);
        DIODE_RH6->setAlignment(Qt::AlignCenter);
        DIODE_RH5 = new QLabel(Diodes);
        DIODE_RH5->setObjectName(QStringLiteral("DIODE_RH5"));
        DIODE_RH5->setGeometry(QRect(280, 170, 30, 50));
        DIODE_RH5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH5->setScaledContents(false);
        DIODE_RH5->setAlignment(Qt::AlignCenter);
        DIODE_RC6 = new QLabel(Diodes);
        DIODE_RC6->setObjectName(QStringLiteral("DIODE_RC6"));
        DIODE_RC6->setGeometry(QRect(80, 210, 30, 50));
        DIODE_RC6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC6->setScaledContents(false);
        DIODE_RC6->setAlignment(Qt::AlignCenter);
        label_183 = new QLabel(Diodes);
        label_183->setObjectName(QStringLiteral("label_183"));
        label_183->setGeometry(QRect(80, 180, 30, 20));
        label_167 = new QLabel(Diodes);
        label_167->setObjectName(QStringLiteral("label_167"));
        label_167->setGeometry(QRect(40, 180, 30, 20));
        DIODE_RE3 = new QLabel(Diodes);
        DIODE_RE3->setObjectName(QStringLiteral("DIODE_RE3"));
        DIODE_RE3->setGeometry(QRect(160, 90, 30, 50));
        DIODE_RE3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE3->setScaledContents(false);
        DIODE_RE3->setAlignment(Qt::AlignCenter);
        DIODE_RC7 = new QLabel(Diodes);
        DIODE_RC7->setObjectName(QStringLiteral("DIODE_RC7"));
        DIODE_RC7->setGeometry(QRect(80, 250, 30, 50));
        DIODE_RC7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC7->setScaledContents(false);
        DIODE_RC7->setAlignment(Qt::AlignCenter);
        label_284 = new QLabel(Diodes);
        label_284->setObjectName(QStringLiteral("label_284"));
        label_284->setGeometry(QRect(320, 20, 30, 20));
        DIODE_RA7 = new QLabel(Diodes);
        DIODE_RA7->setObjectName(QStringLiteral("DIODE_RA7"));
        DIODE_RA7->setGeometry(QRect(0, 250, 30, 50));
        DIODE_RA7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA7->setScaledContents(false);
        DIODE_RA7->setAlignment(Qt::AlignCenter);
        DIODE_RD0 = new QLabel(Diodes);
        DIODE_RD0->setObjectName(QStringLiteral("DIODE_RD0"));
        DIODE_RD0->setGeometry(QRect(120, -30, 30, 50));
        DIODE_RD0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD0->setScaledContents(false);
        DIODE_RD0->setAlignment(Qt::AlignCenter);
        label_144 = new QLabel(Diodes);
        label_144->setObjectName(QStringLiteral("label_144"));
        label_144->setGeometry(QRect(0, 300, 30, 20));
        label_192 = new QLabel(Diodes);
        label_192->setObjectName(QStringLiteral("label_192"));
        label_192->setGeometry(QRect(120, 140, 30, 20));
        DIODE_RA4 = new QLabel(Diodes);
        DIODE_RA4->setObjectName(QStringLiteral("DIODE_RA4"));
        DIODE_RA4->setGeometry(QRect(0, 130, 30, 50));
        DIODE_RA4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA4->setScaledContents(false);
        DIODE_RA4->setAlignment(Qt::AlignCenter);
        DIODE_RF6 = new QLabel(Diodes);
        DIODE_RF6->setObjectName(QStringLiteral("DIODE_RF6"));
        DIODE_RF6->setGeometry(QRect(200, 210, 30, 50));
        DIODE_RF6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF6->setScaledContents(false);
        DIODE_RF6->setAlignment(Qt::AlignCenter);
        DIODE_RC2 = new QLabel(Diodes);
        DIODE_RC2->setObjectName(QStringLiteral("DIODE_RC2"));
        DIODE_RC2->setGeometry(QRect(80, 50, 30, 50));
        DIODE_RC2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC2->setScaledContents(false);
        DIODE_RC2->setAlignment(Qt::AlignCenter);
        DIODE_RH0 = new QLabel(Diodes);
        DIODE_RH0->setObjectName(QStringLiteral("DIODE_RH0"));
        DIODE_RH0->setGeometry(QRect(280, -30, 30, 50));
        DIODE_RH0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH0->setScaledContents(false);
        DIODE_RH0->setAlignment(Qt::AlignCenter);
        label_153 = new QLabel(Diodes);
        label_153->setObjectName(QStringLiteral("label_153"));
        label_153->setGeometry(QRect(0, 100, 30, 20));
        DIODE_RF4 = new QLabel(Diodes);
        DIODE_RF4->setObjectName(QStringLiteral("DIODE_RF4"));
        DIODE_RF4->setGeometry(QRect(200, 130, 30, 50));
        DIODE_RF4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF4->setScaledContents(false);
        DIODE_RF4->setAlignment(Qt::AlignCenter);
        label_216 = new QLabel(Diodes);
        label_216->setObjectName(QStringLiteral("label_216"));
        label_216->setGeometry(QRect(160, 220, 30, 20));
        label_193 = new QLabel(Diodes);
        label_193->setObjectName(QStringLiteral("label_193"));
        label_193->setGeometry(QRect(120, 300, 30, 20));
        DIODE_RC4 = new QLabel(Diodes);
        DIODE_RC4->setObjectName(QStringLiteral("DIODE_RC4"));
        DIODE_RC4->setGeometry(QRect(80, 130, 30, 50));
        DIODE_RC4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC4->setScaledContents(false);
        DIODE_RC4->setAlignment(Qt::AlignCenter);
        DIODE_RB3 = new QLabel(Diodes);
        DIODE_RB3->setObjectName(QStringLiteral("DIODE_RB3"));
        DIODE_RB3->setGeometry(QRect(40, 90, 30, 50));
        DIODE_RB3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB3->setScaledContents(false);
        DIODE_RB3->setAlignment(Qt::AlignCenter);
        label_261 = new QLabel(Diodes);
        label_261->setObjectName(QStringLiteral("label_261"));
        label_261->setGeometry(QRect(280, 60, 30, 20));
        DIODE_RJ4 = new QLabel(Diodes);
        DIODE_RJ4->setObjectName(QStringLiteral("DIODE_RJ4"));
        DIODE_RJ4->setGeometry(QRect(320, 130, 30, 50));
        DIODE_RJ4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ4->setScaledContents(false);
        DIODE_RJ4->setAlignment(Qt::AlignCenter);
        DIODE_RB7 = new QLabel(Diodes);
        DIODE_RB7->setObjectName(QStringLiteral("DIODE_RB7"));
        DIODE_RB7->setGeometry(QRect(40, 250, 30, 50));
        DIODE_RB7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB7->setScaledContents(false);
        DIODE_RB7->setAlignment(Qt::AlignCenter);
        label_205 = new QLabel(Diodes);
        label_205->setObjectName(QStringLiteral("label_205"));
        label_205->setGeometry(QRect(120, 260, 30, 20));
        DIODE_RF5 = new QLabel(Diodes);
        DIODE_RF5->setObjectName(QStringLiteral("DIODE_RF5"));
        DIODE_RF5->setGeometry(QRect(200, 170, 30, 50));
        DIODE_RF5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF5->setScaledContents(false);
        DIODE_RF5->setAlignment(Qt::AlignCenter);
        label_264 = new QLabel(Diodes);
        label_264->setObjectName(QStringLiteral("label_264"));
        label_264->setGeometry(QRect(280, 220, 30, 20));
        DIODE_RA6 = new QLabel(Diodes);
        DIODE_RA6->setObjectName(QStringLiteral("DIODE_RA6"));
        DIODE_RA6->setGeometry(QRect(0, 210, 30, 50));
        DIODE_RA6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA6->setScaledContents(false);
        DIODE_RA6->setAlignment(Qt::AlignCenter);
        label_231 = new QLabel(Diodes);
        label_231->setObjectName(QStringLiteral("label_231"));
        label_231->setGeometry(QRect(200, 180, 30, 20));
        DIODE_RF3 = new QLabel(Diodes);
        DIODE_RF3->setObjectName(QStringLiteral("DIODE_RF3"));
        DIODE_RF3->setGeometry(QRect(200, 90, 30, 50));
        DIODE_RF3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF3->setScaledContents(false);
        DIODE_RF3->setAlignment(Qt::AlignCenter);
        DIODE_RB0 = new QLabel(Diodes);
        DIODE_RB0->setObjectName(QStringLiteral("DIODE_RB0"));
        DIODE_RB0->setGeometry(QRect(40, -30, 30, 50));
        DIODE_RB0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB0->setScaledContents(false);
        DIODE_RB0->setAlignment(Qt::AlignCenter);
        DIODE_RD2 = new QLabel(Diodes);
        DIODE_RD2->setObjectName(QStringLiteral("DIODE_RD2"));
        DIODE_RD2->setGeometry(QRect(120, 50, 30, 50));
        DIODE_RD2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD2->setScaledContents(false);
        DIODE_RD2->setAlignment(Qt::AlignCenter);
        label_157 = new QLabel(Diodes);
        label_157->setObjectName(QStringLiteral("label_157"));
        label_157->setGeometry(QRect(0, 20, 30, 20));
        label_241 = new QLabel(Diodes);
        label_241->setObjectName(QStringLiteral("label_241"));
        label_241->setGeometry(QRect(240, 300, 30, 20));
        DIODE_RB5 = new QLabel(Diodes);
        DIODE_RB5->setObjectName(QStringLiteral("DIODE_RB5"));
        DIODE_RB5->setGeometry(QRect(40, 170, 30, 50));
        DIODE_RB5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB5->setScaledContents(false);
        DIODE_RB5->setAlignment(Qt::AlignCenter);
        label_220 = new QLabel(Diodes);
        label_220->setObjectName(QStringLiteral("label_220"));
        label_220->setGeometry(QRect(160, 20, 30, 20));
        label_151 = new QLabel(Diodes);
        label_151->setObjectName(QStringLiteral("label_151"));
        label_151->setGeometry(QRect(0, 140, 30, 20));
        DIODE_RD4 = new QLabel(Diodes);
        DIODE_RD4->setObjectName(QStringLiteral("DIODE_RD4"));
        DIODE_RD4->setGeometry(QRect(120, 130, 30, 50));
        DIODE_RD4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD4->setScaledContents(false);
        DIODE_RD4->setAlignment(Qt::AlignCenter);
        DIODE_RD5 = new QLabel(Diodes);
        DIODE_RD5->setObjectName(QStringLiteral("DIODE_RD5"));
        DIODE_RD5->setGeometry(QRect(120, 170, 30, 50));
        DIODE_RD5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD5->setScaledContents(false);
        DIODE_RD5->setAlignment(Qt::AlignCenter);
        label_197 = new QLabel(Diodes);
        label_197->setObjectName(QStringLiteral("label_197"));
        label_197->setGeometry(QRect(120, 60, 30, 20));
        DIODE_RH3 = new QLabel(Diodes);
        DIODE_RH3->setObjectName(QStringLiteral("DIODE_RH3"));
        DIODE_RH3->setGeometry(QRect(280, 90, 30, 50));
        DIODE_RH3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH3->setScaledContents(false);
        DIODE_RH3->setAlignment(Qt::AlignCenter);
        DIODE_RD6 = new QLabel(Diodes);
        DIODE_RD6->setObjectName(QStringLiteral("DIODE_RD6"));
        DIODE_RD6->setGeometry(QRect(120, 210, 30, 50));
        DIODE_RD6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD6->setScaledContents(false);
        DIODE_RD6->setAlignment(Qt::AlignCenter);
        DIODE_RE7 = new QLabel(Diodes);
        DIODE_RE7->setObjectName(QStringLiteral("DIODE_RE7"));
        DIODE_RE7->setGeometry(QRect(160, 250, 30, 50));
        DIODE_RE7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE7->setScaledContents(false);
        DIODE_RE7->setAlignment(Qt::AlignCenter);
        label_249 = new QLabel(Diodes);
        label_249->setObjectName(QStringLiteral("label_249"));
        label_249->setGeometry(QRect(240, 100, 30, 20));
        DIODE_RF0 = new QLabel(Diodes);
        DIODE_RF0->setObjectName(QStringLiteral("DIODE_RF0"));
        DIODE_RF0->setGeometry(QRect(200, -30, 30, 50));
        DIODE_RF0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF0->setScaledContents(false);
        DIODE_RF0->setAlignment(Qt::AlignCenter);
        label_184 = new QLabel(Diodes);
        label_184->setObjectName(QStringLiteral("label_184"));
        label_184->setGeometry(QRect(80, 220, 30, 20));
        label_232 = new QLabel(Diodes);
        label_232->setObjectName(QStringLiteral("label_232"));
        label_232->setGeometry(QRect(200, 220, 30, 20));
        label_176 = new QLabel(Diodes);
        label_176->setObjectName(QStringLiteral("label_176"));
        label_176->setGeometry(QRect(80, 140, 30, 20));
        DIODE_RE6 = new QLabel(Diodes);
        DIODE_RE6->setObjectName(QStringLiteral("DIODE_RE6"));
        DIODE_RE6->setGeometry(QRect(160, 210, 30, 50));
        DIODE_RE6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE6->setScaledContents(false);
        DIODE_RE6->setAlignment(Qt::AlignCenter);
        label_215 = new QLabel(Diodes);
        label_215->setObjectName(QStringLiteral("label_215"));
        label_215->setGeometry(QRect(160, 180, 30, 20));
        label_280 = new QLabel(Diodes);
        label_280->setObjectName(QStringLiteral("label_280"));
        label_280->setGeometry(QRect(320, 220, 30, 20));
        label_177 = new QLabel(Diodes);
        label_177->setObjectName(QStringLiteral("label_177"));
        label_177->setGeometry(QRect(80, 300, 30, 20));
        DIODE_RB1 = new QLabel(Diodes);
        DIODE_RB1->setObjectName(QStringLiteral("DIODE_RB1"));
        DIODE_RB1->setGeometry(QRect(40, 10, 30, 50));
        DIODE_RB1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB1->setScaledContents(false);
        DIODE_RB1->setAlignment(Qt::AlignCenter);
        DIODE_RJ6 = new QLabel(Diodes);
        DIODE_RJ6->setObjectName(QStringLiteral("DIODE_RJ6"));
        DIODE_RJ6->setGeometry(QRect(320, 210, 30, 50));
        DIODE_RJ6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ6->setScaledContents(false);
        DIODE_RJ6->setAlignment(Qt::AlignCenter);
        DIODE_RG6 = new QLabel(Diodes);
        DIODE_RG6->setObjectName(QStringLiteral("DIODE_RG6"));
        DIODE_RG6->setGeometry(QRect(240, 210, 30, 50));
        DIODE_RG6->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG6->setScaledContents(false);
        DIODE_RG6->setAlignment(Qt::AlignCenter);
        label_168 = new QLabel(Diodes);
        label_168->setObjectName(QStringLiteral("label_168"));
        label_168->setGeometry(QRect(40, 220, 30, 20));
        label_229 = new QLabel(Diodes);
        label_229->setObjectName(QStringLiteral("label_229"));
        label_229->setGeometry(QRect(200, 60, 30, 20));
        label_165 = new QLabel(Diodes);
        label_165->setObjectName(QStringLiteral("label_165"));
        label_165->setGeometry(QRect(40, 60, 30, 20));
        DIODE_RC0 = new QLabel(Diodes);
        DIODE_RC0->setObjectName(QStringLiteral("DIODE_RC0"));
        DIODE_RC0->setGeometry(QRect(80, -30, 30, 50));
        DIODE_RC0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC0->setScaledContents(false);
        DIODE_RC0->setAlignment(Qt::AlignCenter);
        label_237 = new QLabel(Diodes);
        label_237->setObjectName(QStringLiteral("label_237"));
        label_237->setGeometry(QRect(200, 260, 30, 20));
        label_247 = new QLabel(Diodes);
        label_247->setObjectName(QStringLiteral("label_247"));
        label_247->setGeometry(QRect(240, 180, 30, 20));
        label_181 = new QLabel(Diodes);
        label_181->setObjectName(QStringLiteral("label_181"));
        label_181->setGeometry(QRect(80, 60, 30, 20));
        label_199 = new QLabel(Diodes);
        label_199->setObjectName(QStringLiteral("label_199"));
        label_199->setGeometry(QRect(120, 180, 30, 20));
        label_281 = new QLabel(Diodes);
        label_281->setObjectName(QStringLiteral("label_281"));
        label_281->setGeometry(QRect(320, 100, 30, 20));
        DIODE_RG1 = new QLabel(Diodes);
        DIODE_RG1->setObjectName(QStringLiteral("DIODE_RG1"));
        DIODE_RG1->setGeometry(QRect(240, 10, 30, 50));
        DIODE_RG1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG1->setScaledContents(false);
        DIODE_RG1->setAlignment(Qt::AlignCenter);
        DIODE_RD3 = new QLabel(Diodes);
        DIODE_RD3->setObjectName(QStringLiteral("DIODE_RD3"));
        DIODE_RD3->setGeometry(QRect(120, 90, 30, 50));
        DIODE_RD3->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD3->setScaledContents(false);
        DIODE_RD3->setAlignment(Qt::AlignCenter);
        DIODE_RF2 = new QLabel(Diodes);
        DIODE_RF2->setObjectName(QStringLiteral("DIODE_RF2"));
        DIODE_RF2->setGeometry(QRect(200, 50, 30, 50));
        DIODE_RF2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF2->setScaledContents(false);
        DIODE_RF2->setAlignment(Qt::AlignCenter);
        label_224 = new QLabel(Diodes);
        label_224->setObjectName(QStringLiteral("label_224"));
        label_224->setGeometry(QRect(200, 140, 30, 20));
        DIODE_RA1 = new QLabel(Diodes);
        DIODE_RA1->setObjectName(QStringLiteral("DIODE_RA1"));
        DIODE_RA1->setGeometry(QRect(0, 10, 30, 50));
        DIODE_RA1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA1->setScaledContents(false);
        DIODE_RA1->setAlignment(Qt::AlignCenter);
        label_172 = new QLabel(Diodes);
        label_172->setObjectName(QStringLiteral("label_172"));
        label_172->setGeometry(QRect(40, 20, 30, 20));
        label_233 = new QLabel(Diodes);
        label_233->setObjectName(QStringLiteral("label_233"));
        label_233->setGeometry(QRect(200, 100, 30, 20));
        label_188 = new QLabel(Diodes);
        label_188->setObjectName(QStringLiteral("label_188"));
        label_188->setGeometry(QRect(80, 20, 30, 20));
        label_169 = new QLabel(Diodes);
        label_169->setObjectName(QStringLiteral("label_169"));
        label_169->setGeometry(QRect(40, 100, 30, 20));
        DIODE_RG0 = new QLabel(Diodes);
        DIODE_RG0->setObjectName(QStringLiteral("DIODE_RG0"));
        DIODE_RG0->setGeometry(QRect(240, -30, 30, 50));
        DIODE_RG0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG0->setScaledContents(false);
        DIODE_RG0->setAlignment(Qt::AlignCenter);
        label_253 = new QLabel(Diodes);
        label_253->setObjectName(QStringLiteral("label_253"));
        label_253->setGeometry(QRect(240, 260, 30, 20));
        DIODE_RE5 = new QLabel(Diodes);
        DIODE_RE5->setObjectName(QStringLiteral("DIODE_RE5"));
        DIODE_RE5->setGeometry(QRect(160, 170, 30, 50));
        DIODE_RE5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RE5->setScaledContents(false);
        DIODE_RE5->setAlignment(Qt::AlignCenter);
        DIODE_RB2 = new QLabel(Diodes);
        DIODE_RB2->setObjectName(QStringLiteral("DIODE_RB2"));
        DIODE_RB2->setGeometry(QRect(40, 50, 30, 50));
        DIODE_RB2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RB2->setScaledContents(false);
        DIODE_RB2->setAlignment(Qt::AlignCenter);
        label_263 = new QLabel(Diodes);
        label_263->setObjectName(QStringLiteral("label_263"));
        label_263->setGeometry(QRect(280, 180, 30, 20));
        DIODE_RA0 = new QLabel(Diodes);
        DIODE_RA0->setObjectName(QStringLiteral("DIODE_RA0"));
        DIODE_RA0->setGeometry(QRect(0, -30, 30, 50));
        DIODE_RA0->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RA0->setScaledContents(false);
        DIODE_RA0->setAlignment(Qt::AlignCenter);
        label_285 = new QLabel(Diodes);
        label_285->setObjectName(QStringLiteral("label_285"));
        label_285->setGeometry(QRect(320, 260, 30, 20));
        label_236 = new QLabel(Diodes);
        label_236->setObjectName(QStringLiteral("label_236"));
        label_236->setGeometry(QRect(200, 20, 30, 20));
        label_272 = new QLabel(Diodes);
        label_272->setObjectName(QStringLiteral("label_272"));
        label_272->setGeometry(QRect(320, 140, 30, 20));
        DIODE_RH1 = new QLabel(Diodes);
        DIODE_RH1->setObjectName(QStringLiteral("DIODE_RH1"));
        DIODE_RH1->setGeometry(QRect(280, 10, 30, 50));
        DIODE_RH1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RH1->setScaledContents(false);
        DIODE_RH1->setAlignment(Qt::AlignCenter);
        DIODE_RG4 = new QLabel(Diodes);
        DIODE_RG4->setObjectName(QStringLiteral("DIODE_RG4"));
        DIODE_RG4->setGeometry(QRect(240, 130, 30, 50));
        DIODE_RG4->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RG4->setScaledContents(false);
        DIODE_RG4->setAlignment(Qt::AlignCenter);
        DIODE_RC5 = new QLabel(Diodes);
        DIODE_RC5->setObjectName(QStringLiteral("DIODE_RC5"));
        DIODE_RC5->setGeometry(QRect(80, 170, 30, 50));
        DIODE_RC5->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RC5->setScaledContents(false);
        DIODE_RC5->setAlignment(Qt::AlignCenter);
        DIODE_RD7 = new QLabel(Diodes);
        DIODE_RD7->setObjectName(QStringLiteral("DIODE_RD7"));
        DIODE_RD7->setGeometry(QRect(120, 250, 30, 50));
        DIODE_RD7->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RD7->setScaledContents(false);
        DIODE_RD7->setAlignment(Qt::AlignCenter);
        DIODE_RF1 = new QLabel(Diodes);
        DIODE_RF1->setObjectName(QStringLiteral("DIODE_RF1"));
        DIODE_RF1->setGeometry(QRect(200, 10, 30, 50));
        DIODE_RF1->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RF1->setScaledContents(false);
        DIODE_RF1->setAlignment(Qt::AlignCenter);
        label_200 = new QLabel(Diodes);
        label_200->setObjectName(QStringLiteral("label_200"));
        label_200->setGeometry(QRect(120, 220, 30, 20));
        label_145 = new QLabel(Diodes);
        label_145->setObjectName(QStringLiteral("label_145"));
        label_145->setGeometry(QRect(0, 260, 30, 20));
        label_273 = new QLabel(Diodes);
        label_273->setObjectName(QStringLiteral("label_273"));
        label_273->setGeometry(QRect(320, 300, 30, 20));
        DIODE_RJ2 = new QLabel(Diodes);
        DIODE_RJ2->setObjectName(QStringLiteral("DIODE_RJ2"));
        DIODE_RJ2->setGeometry(QRect(320, 50, 30, 50));
        DIODE_RJ2->setText(QString::fromUtf8("<html><head/><body><p><span style=\" font-size:48pt; color:#740000;\">\342\200\242</span></p></body></html>"));
        DIODE_RJ2->setScaledContents(false);
        DIODE_RJ2->setAlignment(Qt::AlignCenter);
        label_245 = new QLabel(Diodes);
        label_245->setObjectName(QStringLiteral("label_245"));
        label_245->setGeometry(QRect(240, 60, 30, 20));

        retranslateUi(Diodes);

        QMetaObject::connectSlotsByName(Diodes);
    } // setupUi

    void retranslateUi(QWidget *Diodes)
    {
        Diodes->setWindowTitle(QApplication::translate("Diodes", "Form", 0));
        label_155->setText(QApplication::translate("Diodes", "RA1", 0));
        label_161->setText(QApplication::translate("Diodes", "RB7", 0));
        label_248->setText(QApplication::translate("Diodes", "RG5", 0));
        label_213->setText(QApplication::translate("Diodes", "RE1", 0));
        label_147->setText(QApplication::translate("Diodes", "RA5", 0));
        label_252->setText(QApplication::translate("Diodes", "RG0", 0));
        label_240->setText(QApplication::translate("Diodes", "RG3", 0));
        label_221->setText(QApplication::translate("Diodes", "RE6", 0));
        label_209->setText(QApplication::translate("Diodes", "RE7", 0));
        label_265->setText(QApplication::translate("Diodes", "RH2", 0));
        label_217->setText(QApplication::translate("Diodes", "RE2", 0));
        label_201->setText(QApplication::translate("Diodes", "RD2", 0));
        label_256->setText(QApplication::translate("Diodes", "RH3", 0));
        label_160->setText(QApplication::translate("Diodes", "RB3", 0));
        label_185->setText(QApplication::translate("Diodes", "RC2", 0));
        label_204->setText(QApplication::translate("Diodes", "RD0", 0));
        label_268->setText(QApplication::translate("Diodes", "RH0", 0));
        label_189->setText(QApplication::translate("Diodes", "RC6", 0));
        label_257->setText(QApplication::translate("Diodes", "RH7", 0));
        label_173->setText(QApplication::translate("Diodes", "RB6", 0));
        label_149->setText(QApplication::translate("Diodes", "RA4", 0));
        label_277->setText(QApplication::translate("Diodes", "RJ1", 0));
        label_225->setText(QApplication::translate("Diodes", "RF7", 0));
        label_269->setText(QApplication::translate("Diodes", "RH6", 0));
        label_279->setText(QApplication::translate("Diodes", "RJ4", 0));
        label_208->setText(QApplication::translate("Diodes", "RE3", 0));
        label_183->setText(QApplication::translate("Diodes", "RC4", 0));
        label_167->setText(QApplication::translate("Diodes", "RB4", 0));
        label_284->setText(QApplication::translate("Diodes", "RJ0", 0));
        label_144->setText(QApplication::translate("Diodes", "RA7", 0));
        label_192->setText(QApplication::translate("Diodes", "RD3", 0));
        label_153->setText(QApplication::translate("Diodes", "RA2", 0));
        label_216->setText(QApplication::translate("Diodes", "RE5", 0));
        label_193->setText(QApplication::translate("Diodes", "RD7", 0));
        label_261->setText(QApplication::translate("Diodes", "RH1", 0));
        label_205->setText(QApplication::translate("Diodes", "RD6", 0));
        label_264->setText(QApplication::translate("Diodes", "RH5", 0));
        label_231->setText(QApplication::translate("Diodes", "RF4", 0));
        label_157->setText(QApplication::translate("Diodes", "RA0", 0));
        label_241->setText(QApplication::translate("Diodes", "RG7", 0));
        label_220->setText(QApplication::translate("Diodes", "RE0", 0));
        label_151->setText(QApplication::translate("Diodes", "RA3", 0));
        label_197->setText(QApplication::translate("Diodes", "RD1", 0));
        label_249->setText(QApplication::translate("Diodes", "RG2", 0));
        label_184->setText(QApplication::translate("Diodes", "RC5", 0));
        label_232->setText(QApplication::translate("Diodes", "RF5", 0));
        label_176->setText(QApplication::translate("Diodes", "RC3", 0));
        label_215->setText(QApplication::translate("Diodes", "RE4", 0));
        label_280->setText(QApplication::translate("Diodes", "RJ5", 0));
        label_177->setText(QApplication::translate("Diodes", "RC7", 0));
        label_168->setText(QApplication::translate("Diodes", "RB5", 0));
        label_229->setText(QApplication::translate("Diodes", "RF1", 0));
        label_165->setText(QApplication::translate("Diodes", "RB1", 0));
        label_237->setText(QApplication::translate("Diodes", "RF6", 0));
        label_247->setText(QApplication::translate("Diodes", "RG4", 0));
        label_181->setText(QApplication::translate("Diodes", "RC1", 0));
        label_199->setText(QApplication::translate("Diodes", "RD4", 0));
        label_281->setText(QApplication::translate("Diodes", "RJ2", 0));
        label_224->setText(QApplication::translate("Diodes", "RA3", 0));
        label_172->setText(QApplication::translate("Diodes", "RB0", 0));
        label_233->setText(QApplication::translate("Diodes", "RF2", 0));
        label_188->setText(QApplication::translate("Diodes", "RC0", 0));
        label_169->setText(QApplication::translate("Diodes", "RB2", 0));
        label_253->setText(QApplication::translate("Diodes", "RG6", 0));
        label_263->setText(QApplication::translate("Diodes", "RH4", 0));
        label_285->setText(QApplication::translate("Diodes", "RJ6", 0));
        label_236->setText(QApplication::translate("Diodes", "RF0", 0));
        label_272->setText(QApplication::translate("Diodes", "RJ3", 0));
        label_200->setText(QApplication::translate("Diodes", "RD5", 0));
        label_145->setText(QApplication::translate("Diodes", "RA6", 0));
        label_273->setText(QApplication::translate("Diodes", "RJ7", 0));
        label_245->setText(QApplication::translate("Diodes", "RG1", 0));
    } // retranslateUi

};

namespace Ui {
    class Diodes: public Ui_Diodes {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIODES_H
